Exploratory-Data-Analysis(EDA)

Setup library

In [1]:
%pip install -q -U numpy pandas seaborn matplotlib

Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.3 -> 26.1.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
import numpy as np
import pandas as pd
import seaborn as sns

Load Dataset

In [3]:
# Load the built-in Titanic dataset
df = sns.load_dataset('titanic')

# Look at the first 5 rows to understand the columns
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

Adding few columns for demonstrating data issues

In [4]:
df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True

In [14]:
# Add a new column 'passenger_id' with unique values for each passenger
df['passenger_id'] = np.arange(1, len(df)+1)

# Add a constant column with the same value for all rows
df['contant_col'] = 1

#create a dirty version of embark_town column
df['embark_town_dirty'] = df['embark_town'].copy()

# select a few random rows only non-missing values
sample_idx = df['embark_town_dirty'].dropna().sample(6, random_state=42).index

# Apply simple dirty transformations to the selected rows
df.loc[sample_idx [0:2], 'embark_town_dirty'] = df.loc[sample_idx [0:2], 'embark_town_dirty'].str.upper()  # Convert to uppercase
df.loc[sample_idx [2:4], 'embark_town_dirty'] = df.loc[sample_idx [2:4], 'embark_town_dirty'].str.strip().apply(lambda x: f' {x} ')  # Add extra spaces
df.loc[sample_idx [4:6], 'embark_town_dirty'] = 'unknown'  # Replace with unknown

df.head()

,survived,pclass,sex,age,sibsp,parch,fare,embarked,class,who,adult_male,deck,embark_town,alive,alone,passenger_id,contant_col,embark_town_dirty
0,0,3,male,22.0,1,0,7.2500,S,Third,man,True,NaN,Southampton,no,False,1,1,Southampton
1,1,1,female,38.0,1,0,71.2833,C,First,woman,False,C,Cherbourg,yes,False,2,1,Cherbourg
2,1,3,female,26.0,0,0,7.9250,S,Third,woman,False,NaN,Southampton,yes,True,3,1,Southampton
3,1,1,female,35.0,1,0,53.1000,S,First,woman,False,C,Southampton,yes,False,4,1,Southampton
4,0,3,male,35.0,0,0,8.0500,S,Third,man,True,NaN,Southampton,no,True,5,1,Southampton